name: .NET

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'appsettings.Example.json'
      - '.github/**'
      - '.idea/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'appsettings.Example.json'
      - '.github/**'
      - '.idea/**'

permissions:
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: |
          dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --logger "trx" --results-directory "./TestResults"
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Test Results
          path: TestResults/*.trx
          reporter: dotnet-trx
