name: Lint Python

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'frontend/**'

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip flake8
          pip install -r requirements.txt
      - name: Analysing the code with flake8
        if: always()
        run: |
          python -m flake8