name: JavaScript Linting
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - 'frontend/**/*.js'
      - '.github/workflows/lint-js.yml'

  pull_request:
    paths:
      - 'frontend/**/*.js'
      - '.github/workflows/lint-js.yml'

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install all yarn packages
        run: yarn --frozen-lockfile

      - name: ESLint
        run: yarn test:lint:js
