name: CSS Linting
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - 'frontend/**/*.css'
      - 'frontend/**/*.scss'
      - '.github/workflows/lint-css.yml'
      - '.github/stylelint-matcher.json'

  pull_request:
    paths:
      - 'frontend/**/*.css'
      - 'frontend/**/*.scss'
      - '.github/workflows/lint-css.yml'
      - '.github/stylelint-matcher.json'

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install all yarn packages
        run: yarn --frozen-lockfile

      - uses: xt0rted/stylelint-problem-matcher@v1

      - run: echo "::add-matcher::.github/stylelint-matcher.json"

      - name: Stylelint
        run: yarn test:lint:sass
